[package]
name = "sube"
description = "SUBmit Extrinsics to a Substrate node"
license = "Apache-2.0"
version = "0.1.2"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"
repository = "https://github.com/valibre-org/sube"

[dependencies]
async-trait = "0.1.50"
blake2 = { version = "0.9.1", default-features = false }
byteorder = "1.4.3"
frame-metadata = { git = "https://github.com/paritytech/frame-metadata.git", branch = "main", features = ["v12"] }
futures-lite = "1.12.0"
hex = "0.4.3"
jsonrpc = "0.12.0"
log = "0.4.14"
once_cell = "1.8.0"
codec = { version = "2.1.1", package = "parity-scale-codec" }
twox-hash = { version = "1.6.0", default-features = false }
surf = { version = "2.2.0", default_features = false, optional = true }

anyhow = { version = "1.0.41", optional = true }
async-std = { version = "1.9.0", default_features = false }
# async-std = { version = "1.9.0", default_features = false, optional = true }
serde_json = { version = "1.0.64", default-features = false, optional = true }
stderrlog = { version = "0.5.1", optional = true }
structopt = { version = "0.3.21", optional = true }
url = { version = "2.2.2", optional = true }

# async-tungstenite = { version = "0.13.1", features = [], optional = true }
async-tungstenite = { version = "0.13.1", features = ["async-std-runtime"] }
futures-channel = { version = "0.3.15", default-features = false, features = ["alloc"] }
futures-util = { version = "0.3.15", default-features = false, features = ["sink"] }
async-mutex = { version = "1.4.0" }

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }

[features]
default = ["http"]
bin = ["anyhow", "structopt", "async-std/attributes", "stderrlog", "http", "serde_json", "url"]
http = ["surf/h1-client-rustls"]
# ws = ["async-tungstenite"]

[[bin]]
name = "sube"
required-features = ["bin"]
