[package]
name = "sube"
description = "SUBmit Extrinsics to a Substrate node"
license = "Apache-2.0"
version = "0.5.1"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"
repository = "https://github.com/valibre-org/sube"

[dependencies]
async-trait = "0.1.53"
blake2 = { version = "0.10.5", default-features = false }
codec = { version = "3.1.2", package = "parity-scale-codec", default-features = false }
frame-metadata = { version = "15.0.0", default-features = false, features = ["std"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
log = "0.4.17"
once_cell = { version = "1.10.0", default-features = false }
twox-hash = { version = "1.6.2", default-features = false }

scale-info = { version = "2.1.1", optional = true }
jsonrpc = { version = "0.12.1", default-features = false, optional = true }
scales = { version = "1.0.0-beta2", package = "scale-serialization", default-features = false, optional = true }

# http backend
surf = { version = "2.3.2", default_features = false, optional = true }

# ws backend
async-tungstenite = { version = "0.17.2", features = ["async-std-runtime"], optional = true }
futures-channel = { version = "0.3.21", default-features = false, features = ["alloc"], optional = true }
futures-util = { version = "0.3.21", default-features = false, features = ["sink"], optional = true }
async-mutex = { version = "1.4.0", optional = true }
async-tls = { version = "0.11.0", default-features = false, optional = true }

# bin target
anyhow = { version = "1.0.57", optional = true }
async-std = { version = "1.11.0", default_features = false, optional = true }
serde_json = { version = "1.0.80", default-features = false, optional = true }
stderrlog = { version = "0.5.1", optional = true }
structopt = { version = "0.3.26", optional = true }
url = { version = "2.2.2", optional = true }
serde = { version = "1.0.137", default-features = false, optional = true }

[dev-dependencies]
async-std = { version = "1.11.0", features = ["attributes"] }
hex-literal = "0.3.4"

[features]
default = ["bin", "json", "std"]
#default = ["v14", "ws", "decode", "json", "std"]
bin = [
	"anyhow",
	"async-std/attributes",
	"http",
	"decode",
	"encode",
	"serde",
	"serde_json",
	"scales/hex",
	"std",
	"stderrlog",
	"structopt",
	"url",
	"v14",
	"wss",
]
decode = ["v14", "serde", "scales/codec"]
encode = ["v14", "scales/experimental-serializer"]
http = ["jsonrpc", "surf/h1-client-rustls"]
http-web = ["jsonrpc", "surf/wasm-client"]
json = ["v14", "scales/json"]
std = []
v12 = ["frame-metadata/v12"]
v13 = ["frame-metadata/v13"]
v14 = ["frame-metadata/v14", "scale-info", "scales"]
ws = ["async-std", "async-tungstenite", "async-mutex", "futures-util", "futures-channel", "jsonrpc"]
wss = ["ws", "async-tls", "async-tungstenite/async-tls"]

[[bin]]
name = "sube"
required-features = ["bin"]

[package.metadata.docs.rs]
features = ["http"]
