on: 
  pull_request:
    paths: ['scales/**']

name: Scales

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v2
      - name: Check
        run: just -f lib/scales/justfile check
      - name: Lint
        run: just -f lib/scales/justfile lint
   
  test:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v2
      - name: Test
        run: just -f lib/scales/justfile test
