on: 
  pull_request:
    paths: ['sube/**']

name: Sube

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v2
      - name: Check
        run: just -f lib/sube/justfile check
      - name: Lint
        run: just -f lib/sube/justfile lint
