[package]
name = "vos"
version = "0.1.0"
edition = "2021"

[dependencies]
matrix-sdk = "0.7.1"
nu-engine = "0.96.1"
polkavm = { version = "0.10.0", optional = true }
tokio = { version = "1.39.3", features = ["macros", "rt-multi-thread"] }

[features]
# default = ["std"]
std = ["dep:polkavm"]
